### ISSUE TITLE
Changes for the [FILE] tag

### ISSUE THREAD

**Issue by alexroston** [Frechdachs/mpvQC#3]
It would be cool if the name of the QC text file (at least the one when saving it the first time) could be added under the [FILE] tag.
Besides I think kSub had an option to remove the path of the saved QC file. This option would also be great so that I don't have to show my personal folder structure to everyone reading the QC file.

**Comment by Frechdachs** [comment]
Yeah, adding an option to disable the storage of the file path is something I have planned.

But I don't get why you want the file name of the QC document saved in its header.

**Comment by Frechdachs** [comment]
Implemented.
