### ISSUE TITLE
libmpv.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Linus789** [Frechdachs/mpvQC#5]
``linus@Linus-desktop ~/Dokumente/mpvQC/mpvQC-0.5.1 $ python3 mpvQC.py 
Traceback (most recent call last):
  File "mpvQC.py", line 17, in <module>
    import mpv  # https://github.com/jaseg/python-mpv
  File "/home/linus/Dokumente/mpvQC/mpvQC-0.5.1/mpv.py", line 46, in <module>
    backend = CDLL(sofile)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpv.so.1: cannot open shared object file: No such file or directory``

I'm using linux mint 18 and did everything after the Debian/Ubuntu tutorial. How can I get rid of this error?

**Comment by Frechdachs** [comment]
The problems seems to be that it does not find libmpv.

First, try git master instead of 0.5.1 or this fork that will be merged soon: https://github.com/trin94/mpvQC
Then check if there actually is a libmpv.so(.1) on your system. `sudo ./install` should have installed it to `/usr/local/lib/`.
If it is there, try adding it to your PATH.

**Comment by Linus789** [comment]
`linus@Linus-desktop /usr/local/lib $ ls
libmpv.so  libmpv.so.1  libmpv.so.1.101.0  libpython3.6m.a  node_modules  pkgconfig  python2.7  python3.5  python3.6`

`linus@Linus-desktop ~/Dokumente/mpvQC/ $ PATH=$PATH:/usr/local/lib/`

From version 0.5.1:
`linus@Linus-desktop ~/Dokumente/mpvQC/mpvQC-0.5.1 $ python3 mpvQC.py 
Traceback (most recent call last):
  File "mpvQC.py", line 17, in <module>
    import mpv  # https://github.com/jaseg/python-mpv
  File "/home/linus/Dokumente/mpvQC/mpvQC-0.5.1/mpv.py", line 46, in <module>
    backend = CDLL(sofile)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpv.so.1: cannot open shared object file: No such file or directory`

From trin94 mpvQC:
`linus@Linus-desktop ~/Dokumente/mpvQC/mpvQC-master-new $ python3 start.py 
Traceback (most recent call last):
  File "start.py", line 24, in <module>
    from src import gui
  File "/home/linus/Dokumente/mpvQC/mpvQC-master-new/src/gui/__init__.py", line 29
    TYPEWRITER_FONT: QFont
                   ^
SyntaxError: invalid syntax`

**Comment by Frechdachs** [comment]
Ah, yeah, trin94's branch needs python 3.6.

Anyway, try inspecting what is inside the variable `sofile` in mpv.py, normally it should be None if it does not find libmpv.so, but apparently it is not in your case.
You can also try putting the path to libmpv.so inside `CDLL` directly in mpv.py, I'd be interested if that solves the problem.

**Comment by Linus789** [comment]
The sofile is not _None_, if I print it out: `libmpv.so.1`
How to import directly, which command is it?
Tomorrow I'll try install python 3.6

**Comment by Frechdachs** [comment]
Change
```python
backend = CDDL(sofile)
```
to
```python
backend = CDLL('/usr/local/lib/libmpv.so')
```
in `mpv.py`
or if you use trin94's branch in `src/player/bindings.py`

This will definitely solve your problem.
It seems that `ctypes.util.find_library` does find `libmpv` but `CDLL` for some reason does not, so it still looks like that your PATH is not set correctly.

**Comment by Linus789** [comment]
Strange. Suddenly the release 0.5.1 works (Perhaps I updated Python on my system? I don't really remember), but when I download the master I still get an error. Anyway, thanks for your help, it's working now!
